//! The AI agent's context file. Castline writes a `CLAUDE.md` into the data dir
//! (the PTY's cwd) so the embedded `claude` knows what the app is, where the
//! data lives, and — crucially — how to **write** safely: it creates/enriches
//! profiles by POSTing to the local HTTP endpoint (Rust stays the only writer,
//! so the JSON never gets hand-corrupted and the UI updates live).

use std::fs;
use std::io;
use std::path::Path;

/// What the agent needs to know to write back into Castline.
pub struct AgentContext {
    /// Absolute path to the data dir (where library.json / profiles.json live).
    pub data_dir: String,
    /// e.g. `http://127.0.0.1:8787` — the inbound endpoint base.
    pub base_url: String,
    /// Bearer token for the endpoint (empty if the endpoint is off).
    pub token: String,
    /// Whether the endpoint is currently listening.
    pub endpoint_on: bool,
}

/// Write atomically (tmp + rename) so the agent never reads a torn file.
fn write_atomic(path: &Path, content: &str) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension("md.tmp");
    fs::write(&tmp, content)?;
    fs::rename(&tmp, path)
}

/// Render + write the workspace CLAUDE.md. Regenerated on every agent start /
/// context refresh (durable notes go in MEMORY.md, which we never overwrite).
pub fn write_claude_md(root: &Path, ctx: &AgentContext) -> io::Result<()> {
    write_atomic(&root.join("CLAUDE.md"), &render_claude_md(ctx))
}

fn render_claude_md(ctx: &AgentContext) -> String {
    let write_section = if ctx.endpoint_on && !ctx.token.is_empty() {
        format!(
            "The endpoint is **on**. Create or enrich profiles by POSTing JSON to it — do **not**\n\
             hand-edit `profiles.json` (Castline is the only writer, keeps ids consistent, and the UI\n\
             refreshes live only for changes made through the endpoint).\n\n\
             Base URL: `{base}`  ·  Auth header: `Authorization: Bearer {token}`\n\n\
             **Create a profile** (every JSON key becomes a variable of the same name; `name`, or\n\
             `first_name`+`last_name`, sets the display name):\n\n\
             ```bash\n\
             curl -sS -X POST \"{base}/api/create-profile\" \\\n\
               -H \"Authorization: Bearer {token}\" \\\n\
               -H \"Content-Type: application/json\" \\\n\
               -d '{{\"first_name\":\"Sam\",\"last_name\":\"Rivera\",\"company\":\"Acme\",\"email\":\"sam@acme.com\"}}'\n\
             ```\n\n\
             **Enrich an existing profile** (merges the JSON into the profile matched by `name`\n\
             case-insensitively, or by a shared `email`; 404 if none matches):\n\n\
             ```bash\n\
             curl -sS -X POST \"{base}/api/update-profile\" \\\n\
               -H \"Authorization: Bearer {token}\" \\\n\
               -H \"Content-Type: application/json\" \\\n\
               -d '{{\"email\":\"sam@acme.com\",\"title\":\"CTO\",\"linkedin\":\"https://…\"}}'\n\
             ```\n\n\
             A `200 {{\"ok\":true,...}}` means it worked and the profile is already visible in the app.\n",
            base = ctx.base_url,
            token = ctx.token,
        )
    } else {
        "The local write endpoint is currently **off**, so you can only read for now. Ask the user to\n\
         open **Connectors → HTTP endpoint (inbound)** and switch it on; then you can create/enrich\n\
         profiles by POSTing to `http://127.0.0.1:<port>/api/create-profile` (and `/api/update-profile`)\n\
         with the bearer token shown there.\n"
            .to_string()
    };

    format!(
        "<!-- Generated by Castline on every agent start / context refresh — edits here will be\n\
         overwritten. Durable notes belong in MEMORY.md. -->\n\n\
# Castline — agent guide\n\n\
This folder is the data directory of **Castline**, a local-first desktop app for storing reusable text\n\
(prompts, templates, notes, multi-step SOPs) with live `{{{{variables}}}}` and reusable **profiles**\n\
(named sets of variable values — a client, a project, a person). You are an embedded assistant launched\n\
in this folder; your main job is to help the user **gather data and enrich their profiles**.\n\n\
## Where the data lives (read these for context — do not hand-edit)\n\n\
- `{dir}/library.json` — the text library: `{{ \"folders\": [ {{ id, name, color, icon,\n\
  items: [ {{ id, name, kind: \"template\"|\"sop\", text, steps, tags, type, favorite }} ] }} ] }}`.\n\
- `{dir}/profiles.json` — the profiles: `{{ \"profiles\": [ {{ id, name, values: {{ variableName:\n\
  value }}, source }} ], \"layout\": [...] }}`. `values` keys are the `{{{{variable}}}}` names used across\n\
  the library; `layout` is presentation-only grouping (ignore it when writing).\n\
- `MEMORY.md` — **yours**: append durable facts about the user (preferences, recurring clients, goals).\n\
  Castline writes the template once and never touches it again.\n\n\
To see which variables profiles should fill, read the `text`/`steps` in `library.json` and collect the\n\
`{{{{...}}}}` tokens. Prefer reading the JSON directly; use `jq` if it's available.\n\n\
## Writing back: create / enrich profiles via the local HTTP endpoint\n\n\
{write_section}\n\
## Your role\n\n\
- When asked to research a person/company, use whatever tools you have (the user's own CLIs / MCP\n\
  servers, web access if configured) to gather fields, then **create or enrich the matching profile**\n\
  through the endpoint above.\n\
- Map everything to the variable names already used in the library so the profile actually fills the\n\
  templates. Add new fields freely — unknown keys just become new variables.\n\
- Be conservative: confirm with the user before creating many profiles at once, and prefer enriching an\n\
  existing profile over creating a duplicate. Record durable observations in MEMORY.md.\n",
        dir = ctx.data_dir,
        write_section = write_section,
    )
}

/// Write the MEMORY.md template only if it doesn't exist yet; the agent owns it
/// afterwards and Castline never overwrites it.
pub fn ensure_memory_md(root: &Path) -> io::Result<()> {
    let path = root.join("MEMORY.md");
    if path.exists() {
        return Ok(());
    }
    fs::create_dir_all(root)?;
    fs::write(
        &path,
        "# Memory\n\n\
This file belongs to the AI assistant. Castline wrote this template once and will never touch it\n\
again — append or reorganize freely. Keep it to durable, load-bearing facts about the user and their\n\
contacts; everything ephemeral belongs in conversation.\n\n\
## About the user\n\n\
## Recurring clients / contacts\n\n\
## Preferences\n",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ctx(on: bool) -> AgentContext {
        AgentContext {
            data_dir: "C:/data/Castline".into(),
            base_url: "http://127.0.0.1:8787".into(),
            token: if on { "secret-token-123".into() } else { String::new() },
            endpoint_on: on,
        }
    }

    #[test]
    fn claude_md_documents_paths_endpoints_and_token() {
        let tmp = tempfile::tempdir().unwrap();
        write_claude_md(tmp.path(), &ctx(true)).unwrap();
        let text = fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
        for needle in [
            "library.json",
            "profiles.json",
            "/api/create-profile",
            "/api/update-profile",
            "secret-token-123",
            "http://127.0.0.1:8787",
            "MEMORY.md",
        ] {
            assert!(text.contains(needle), "CLAUDE.md missing {needle}");
        }
        // Atomic write left no temp file behind.
        assert!(!tmp.path().join("CLAUDE.md.tmp").exists());
    }

    #[test]
    fn claude_md_without_endpoint_tells_agent_to_enable_it() {
        let tmp = tempfile::tempdir().unwrap();
        write_claude_md(tmp.path(), &ctx(false)).unwrap();
        let text = fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
        assert!(text.contains("currently **off**"));
        assert!(!text.contains("secret-token-123"));
    }

    #[test]
    fn memory_md_never_overwritten() {
        let tmp = tempfile::tempdir().unwrap();
        ensure_memory_md(tmp.path()).unwrap();
        fs::write(tmp.path().join("MEMORY.md"), "# Memory\n\nuser likes terse answers\n").unwrap();
        ensure_memory_md(tmp.path()).unwrap();
        let text = fs::read_to_string(tmp.path().join("MEMORY.md")).unwrap();
        assert!(text.contains("terse answers"));
    }
}
